### PR TITLE
Prefix route for metrics

### PR DESCRIPTION
**Pull request by doojonio**
I think it's good idea to give the opportunity to create prefix-route for metrics. This can help when setting up basic auth.

### CODE REVIEW

**Comment by tyldum** [comment]
Good idea. I'm thinking $config->{route} should be a `Mojolicious::Routes::Route` object, that way you can combine it with `under`.
Could you update with that and add documentation?

**Comment by doojonio** [comment]
> Good idea. I'm thinking $config->{route} should be a `Mojolicious::Routes::Route` object, that way you can combine it with `under`.

I'm not sure I understood you correctly, but i did something that works for me :)

**Comment by doojonio** [comment]
I see it as in [Mojolicious::Plugin::Minion::Admin](https://metacpan.org/pod/Mojolicious::Plugin::Minion::Admin)

**Comment by tyldum** [comment]
Actually, it should already work like that. Did you try configuring the
plugin using `route` instead of `prefix`?

søn. 12. apr. 2020, 16:46 skrev Anton Fedotov <notifications@github.com>:

**Comment by tyldum** [comment]
Looks good, added simple test.

**Pull request merged**
